# Generated by Django 4.2.6 on 2023-10-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дайте описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_page',
            field=models.IntegerField(null=True, verbose_name='Укажите колличество страниц'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_book',
            field=models.CharField(choices=[('Фантастика', 'Фанатастика'), ('Художественная', 'Художественная'), ('Хоррор', 'Хоррор'), ('Фентези', 'Фентези')], max_length=100, null=True, verbose_name='выебрите жанр'),
        ),
    ]
