# Generated by Django 4.2.6 on 2023-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_alter_post_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Укажите дату издания'),
        ),
    ]
